dist: trusty
sudo: false
language: python
cache: pip
services:
  - postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - OEP_DB_USER="postgres" OEP_DB_PW="postgres"
    - LOCAL_DB_USER="postgres" LOCAL_DB_PASSWORD="postgres"
    - LOCAL_OEP_USER="user" LOCAL_OEP_TOKEN="token"
  matrix:
    - TOXENV=check
    - TOXENV=docs
matrix:
  include:
    - python: '3.5'
      env:
        - TOXENV=py3
    - python: '3.6'
      env:
        - TOXENV=py3
before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - sudo apt-get update
install:
  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

before_script:
  - psql -U postgres -c 'CREATE DATABASE test;'
  - psql -U postgres -c "CREATE EXTENSION postgis;" test
  - psql -U postgres -c "CREATE DATABASE oedb"
  - psql -U postgres -c "CREATE EXTENSION postgis;" oedb
  - psql -U postgres -c "CREATE DATABASE oep_django"
  - git clone https://github.com/OpenEnergyPlatform/oeplatform.git oep
  - cd oep
  - pip install -r requirements.txt
  - cp oeplatform/securitysettings.py.default oeplatform/securitysettings.py
  - python manage.py migrate
  - python manage.py alembic upgrade head
  - python manage.py shell -c "from login.models import myuser, Token; u=myuser.objects.create_user(name='$LOCAL_OEP_USER',email='test@test.com');t=Token.objects.create(user=u);t.key='$LOCAL_OEP_TOKEN';t.save();u.save()"
  - python manage.py runserver
  - cd ..

script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always