[project]
name = "oedialect"
version = "0.1.0"
authors = [
    {name = "MGlauer", email = "martinglauer89@gmail.com"}
]
urls = {Homepage = "https://github.com/openego/oedialect"}
description = "SQL-Alchemy dialect for the OpenEnergy Platform"
readme = "README.md"
requires-python = ">=3.9"
keywords = ["postgres", "open", "energy", "database", "sql", "rest"]

dependencies = [
    "GeoAlchemy2~=0.17",
    "psycopg2-binary~=2.9",
    "python-dateutil~=2.9",
    "requests~=2.32",
    "Shapely~=2.0",
    # TODO: the problem is when upgrading to 1.4
    "SQLAlchemy~=2.0"
]

[project.optional-dependencies]
dev = [
  # pytest>=7 not working with old sqlalchemy testing
  "pytest~=8.4",
  # tox not working yet
  "tox"
]


[project.entry-points."sqlalchemy.dialects"]
"postgres.oedialect" = "oedialect.dialect:OEDialect"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
