[project]
name = "oedialect"
version = "0.1.0"
authors = [
    {name = "MGlauer", email = "martinglauer89@gmail.com"}
]
urls = {Homepage = "https://github.com/openego/oedialect"}
description = "SQL-Alchemy dialect for the OpenEnergy Platform"

readme = "README.md"

# NOTE: the old tests only work in 3.9
requires-python = "~=3.9"

keywords = ["postgres", "open", "energy", "database", "sql", "rest"]
dependencies = [
    "GeoAlchemy2",
    "psycopg2-binary",
    "python-dateutil",
    "requests",
    "Shapely",
    "SQLAlchemy<1.4"
]

[project.optional-dependencies]
dev = [
  "pytest==5.3",
  "tox"
]

[tool.tox]
envlist = ["py39"]

[tool.tox.testenv]
deps = ["pytest"]
commands = ["pytest"]