[project]
name = "oedialect"
version = "0.1.0"
authors = [
    {name = "MGlauer", email = "martinglauer89@gmail.com"}
]
urls = {Homepage = "https://github.com/openego/oedialect"}
description = "SQL-Alchemy dialect for the OpenEnergy Platform"

readme = "README.md"

# NOTE: the old tests only work in 3.9
requires-python = "~=3.9"

keywords = ["postgres", "open", "energy", "database", "sql", "rest"]
dependencies = [
    "GeoAlchemy2~=0.11",
    "psycopg2-binary~=2.9",
    "python-dateutil~=2.9",
    "requests~=2.32",
    "Shapely~=2.0",
    # TODO: the problem is when upgrading to 1.4
    "SQLAlchemy==1.3.24"
]

[project.optional-dependencies]
dev = [
  "pytest<6",
  # tox not working yet
  "tox"
]
